<HTML>
<head>
    <link rel="stylesheet" type="text/css" href="css.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />
</head>

    <body>

        <form action="index.php">
            <table>
                <thead>
                    <tr>
                        <td>Show region data:</td>
                        <td>Select sources:</td>
                        <td>Price:</td>
                        <td>Code unique:</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="text-align: center">
                            <select title="Region"  name="group[]" multiple style="width: 150px;" id="region_europe">
                                <option value="europe" <?php if(!empty($_GET['group']) && is_array($_GET['group']) && in_array('europe', $_GET['group'])){echo 'selected';} ?>>Europe</option>
                                <option value="world" <?php if(!empty($_GET['group']) && is_array($_GET['group']) && in_array('world', $_GET['group'])){echo 'selected';} ?>>World</option>
                            </select>
                        </td>
                        <td style="text-align: center">
                            <select title="Sources" name="source[]" multiple style="width: 150px;">
                                <option value="php" <?php if(!empty($_GET['source']) && is_array($_GET['source']) && in_array('php', $_GET['source'])){echo 'selected';} ?>>PHP</option>
                                <option value="json" <?php if(!empty($_GET['source']) && is_array($_GET['source']) && in_array('json', $_GET['source'])){echo 'selected';} ?>>JSON</option>
                                <option value="xml" <?php if(!empty($_GET['source']) && is_array($_GET['source']) && in_array('xml', $_GET['source'])){echo 'selected';} ?>>XML</option>
                            </select>
                        </td>
                        <td style="text-align: center">
                            <select name="price_condition">
                                <option value="">
                                <option value="more" <?php if(!empty($_GET['price_condition']) && $_GET['price_condition'] == 'more' ){echo 'selected';} ?>>More than:
                                <option value="less" <?php if(!empty($_GET['price_condition']) && $_GET['price_condition'] == 'less' ){echo 'selected';} ?>>Less than:
                            </select>
                            <input type="text" name="price_value" value="<?php if(!empty($_GET['price_value']) && is_numeric($_GET['price_value']) ){echo $_GET['price_value'];} ?>">
                        </td>
                        <td style="text-align: center">
                            <input type="checkbox" name="code_unique" value="true" <?php if($_GET['code_unique']=='true'){echo 'checked';} ?> ><br>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="4" style="text-align: center">
                            Sort by: <select name="sort_field">
                                <option value="">
                                <option value="price" <?php if(!empty($_GET['sort_field']) && $_GET['sort_field'] == 'price'){echo 'selected';} ?>>Price
                                <option value="code"  <?php if(!empty($_GET['sort_field']) && $_GET['sort_field'] == 'code'){echo 'selected';} ?>>Code
                                <option value="name"  <?php if(!empty($_GET['sort_field']) && $_GET['sort_field'] == 'name'){echo 'selected';} ?>>Name
                            </select>

                            Sort order: <select name="sort_order">
                                <option value="">
                                <option value="desc" <?php if(!empty($_GET['sort_order']) && $_GET['sort_order'] == 'desc' ){echo 'selected';} ?>>DESC
                                <option value="asc" <?php if(!empty($_GET['sort_order']) && $_GET['sort_order'] == 'asc' ){echo 'selected';} ?>>ASC
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="4" style="text-align: right">
                            <input type="submit">
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>

            <div id="tableResult">
                <?= $objView->buildTable($fullDataArray) ?>
            </div>

    </body>
</HTML>